# https://docs.spring.io/spring-boot/docs/2.7.6/reference/html/application-properties.html#appendix.application-properties
# profile 공통
spring:
    profiles:
        active: dev # 동작 할 profile

server:
    port: 8000 # spring boot port 설정
---
# dev profiles
spring:
    profiles: 
        activate:
            on-profile: dev
    # DB접속정보
    datasource: 
        driver-class-name: com.mysql.cj.jdbc.Driver #JDBC 드라이버의 완전한 이름입니다. 기본적으로 URL을 기반으로 자동 감지
        url: jdbc:mysql://35.73.210.60:3306/my_rds_name?serverTimezone=Asia/Seoul # DB 주소
        username: admin
        password: qwer!234    

    jpa:
        open-in-view: true # https://xzio.tisotry.com/2052
        hibernate:
            ddl-auto: create # 스프링부트 실행 시 기존 Entity 삭제 후 재생성
            naming: # Entity를 테이블로 만들 때 테이블/컬럼 네이밍 룰
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity 명을 그대로 따름
            use-new-id-generator-mappings: false # hibernate의 ID생성전략 사용여부. (@GeneratedValue(GenerationType.AUTO 등))
        show-sql: false # hibernate sql 쿼리 로깅
        properties:
            "[hibernate.format_sql]": true # SQL 쿼리 포맷팅
            
logging:
    level:
        "[org.hibernate.SQL]": debug # jpa.show-sql=true 하고 중첩 됨. 둘중 하나는 끄는게 좋음.
        "[org.hibernate.type]": trace # hibernate 쿼리에 바인딩 된 파라미터 값

